### ISSUE TITLE
/usr/sbin/varnishreload: No such file or directory

### ISSUE THREAD

**Issue by Bilge** [geerlingguy/ansible-role-varnish#115]
On Ubuntu Jammy using the stock Varnish 6.6.1, `varnishreload` does not exist at `/usr/sbin`, so the reload command (`systemctl reload varnish`) fails. It is instead located at `/usr/share/varnish/varnishreload`.

We can use the distro default package (to reproduce this issue) by setting the configuration variable like so:
```yaml
- import_role: name=geerlingguy.varnish
  vars:
    varnish_apt_repo: deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe
```
