### ISSUE TITLE
Varnish 5.0 is here!

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-varnish#39]
See: http://varnish.org/docs/5.0/whats-new/upgrading-5.0.html#whatsnew-upgrading-5-0

Still need to fix up a couple things for 4.1 as well, but it looks like 5.0 won't be as far-reaching as 4.0 was in terms of VCL changes.

**Comment by geerlingguy** [comment]
It looks like it's not yet in the repos (only available from source builds):

  - https://repo.varnish-cache.org/redhat/ — no 5.x package available yet.
  - http://repo.varnish-cache.org/ubuntu/dists/trusty/InRelease - no 5.x package available yet.

**Comment by geerlingguy** [comment]
See: https://github.com/varnishcache/pkg-varnish-cache/issues/45

**Comment by geerlingguy** [comment]
Apparently for 5.x, there's a new directory structure: https://repo.varnish-cache.org/pkg/5.0.0/

**Comment by geerlingguy** [comment]
Got it working on CentOS 6/7:

```
$ sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm varnishd -V
varnishd (varnish-5.0.0 revision 99d036f)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS
```

**Comment by geerlingguy** [comment]
And on Ubuntu 16/14:

```
$ sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm varnishd -V
varnishd (varnish-5.0.0 revision 99d036f)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS
```

And Debian 8:

```
0.09s$ sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm varnishd -V
varnishd (varnish-5.0.0 revision 99d036f)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS
```

**Comment by geerlingguy** [comment]
Now, the trick is to be able to support both 4.x and 5.x at the same time. I'll have to have two sets of install tasks for both RedHat and Debian unless and until Varnish adds back in normal yum/apt repos...

**Comment by geerlingguy** [comment]
Looks like there is a repo now... https://packagecloud.io/varnishcache/varnish5#readme-scrollto

**Comment by mathieumd** [comment]
It seems that starting with 5.0, the official repo is now at packagecloud.io, for both [Debian](https://www.varnish-cache.org/releases/install_debian.html#install-debian) and [RHEL](https://www.varnish-cache.org/releases/install_redhat.html#install-redhat).

Something like that should do it for the bare installation on Debian:

```yaml
- name: Add packagecloud.io apt key.
  apt_key:
    url: https://packagecloud.io/varnishcache/varnish5/gpgkey
    state: present
  when: ansible_distribution_release != "xenial" and varnish_version|int >= 5

- name: Add Varnish apt repository.
  apt_repository:
    repo: "deb https://repo.varnish-cache.org/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} varnish-{{ varnish_version }}"
    state: present
  when: ansible_distribution_release != "xenial" and varnish_version|int < 5

- name: Add Varnish 5+ apt repository.
  apt_repository:
    repo: "deb https://packagecloud.io/varnishcache/varnish5/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main"
    state: present
  when: ansible_distribution_release != "xenial" and varnish_version|int >= 5
```
Tested and validated for debian8 with your (very nice) test.sh.
