### ISSUE TITLE
task "Ensure Varnish services are started and enabled on startup." is skipped on Ubuntu Bionic

### ISSUE THREAD

**Issue by it-percona** [geerlingguy/ansible-role-varnish#92]
There is a check for ansible_os_family that restricts this working on Ubuntu bionic
```
- name: Ensure Varnish services are started and enabled on startup.
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ varnish_enabled_services | default([]) }}"
  when: >
    varnish_enabled_services and
    (ansible_os_family != 'Debian' and ansible_distribution_release != "xenial")
```

Should just be:
```
- name: Ensure Varnish services are started and enabled on startup.
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ varnish_enabled_services | default([]) }}"
  when: >
    varnish_enabled_services and (ansible_os_family != 'Debian' or
    (ansible_os_family == 'Debian' and ansible_distribution_release != "xenial"))
```
